.pragma library

var media =
        {"asme_f_28x40in": qsTr("28 x 40″"),
         "iso_2a0_1189x1682mm": qsTr("2a0"),
         "iso_a0_841x1189mm": qsTr("A0"),
         "iso_a0x3_1189x2523mm": qsTr("A0x3"),
         "iso_a10_26x37mm": qsTr("A10"),
         "iso_a1_594x841mm": qsTr("A1"),
         "iso_a1x3_841x1783mm": qsTr("A1x3"),
         "iso_a1x4_841x2378mm": qsTr("A1x4"),
         "iso_a2_420x594mm": qsTr("A2"),
         "iso_a2x3_594x1261mm": qsTr("A2x3"),
         "iso_a2x4_594x1682mm": qsTr("A2x4"),
         "iso_a2x5_594x2102mm": qsTr("A2x5"),
         "iso_a3-extra_322x445mm": qsTr("A3 (Extra)"),
         "iso_a3_297x420mm": qsTr("A3"),
         "iso_a3x3_420x891mm": qsTr("A3x3"),
         "iso_a3x4_420x1189mm": qsTr("A3x4"),
         "iso_a3x5_420x1486mm": qsTr("A3x5"),
         "iso_a3x6_420x1783mm": qsTr("A3x6"),
         "iso_a3x7_420x2080mm": qsTr("A3x7"),
         "iso_a4-extra_235.5x322.3mm": qsTr("A4 (Extra)"),
         "iso_a4-tab_225x297mm": qsTr("A4 (Tab)"),
         "iso_a4_210x297mm": qsTr("A4"),
         "iso_a4x3_297x630mm": qsTr("A4x3"),
         "iso_a4x4_297x841mm": qsTr("A4x4"),
         "iso_a4x5_297x1051mm": qsTr("A4x5"),
         "iso_a4x6_297x1261mm": qsTr("A4x6"),
         "iso_a4x7_297x1471mm": qsTr("A4x7"),
         "iso_a4x8_297x1682mm": qsTr("A4x8"),
         "iso_a4x9_297x1892mm": qsTr("A4x9"),
         "iso_a5-extra_174x235mm": qsTr("A5 (Extra)"),
         "iso_a5_148x210mm": qsTr("A5"),
         "iso_a6_105x148mm": qsTr("A6"),
         "iso_a7_74x105mm": qsTr("A7"),
         "iso_a8_52x74mm": qsTr("A8"),
         "iso_a9_37x52mm": qsTr("A9"),
         "iso_b0_1000x1414mm": qsTr("B0"),
         "iso_b10_31x44mm": qsTr("B10"),
         "iso_b1_707x1000mm": qsTr("B1"),
         "iso_b2_500x707mm": qsTr("B2"),
         "iso_b3_353x500mm": qsTr("B3"),
         "iso_b4_250x353mm": qsTr("B4"),
         "iso_b5-extra_201x276mm": qsTr("B5 (Extra)"),
         "iso_b5_176x250mm": qsTr("Envelope B5"),
         "iso_b6_125x176mm": qsTr("B6"),
         "iso_b6c4_125x324mm": qsTr("Envelope B6/C4"),
         "iso_b7_88x125mm": qsTr("B7"),
         "iso_b8_62x88mm": qsTr("B8"),
         "iso_b9_44x62mm": qsTr("B9"),
         "iso_c0_917x1297mm": qsTr("CEnvelope 0"),
         "iso_c10_28x40mm": qsTr("CEnvelope 10"),
         "iso_c1_648x917mm": qsTr("CEnvelope 1"),
         "iso_c2_458x648mm": qsTr("CEnvelope 2"),
         "iso_c3_324x458mm": qsTr("CEnvelope 3"),
         "iso_c4_229x324mm": qsTr("CEnvelope 4"),
         "iso_c5_162x229mm": qsTr("CEnvelope 5"),
         "iso_c6_114x162mm": qsTr("CEnvelope 6"),
         "iso_c6c5_114x229mm": qsTr("CEnvelope 6c5"),
         "iso_c7_81x114mm": qsTr("CEnvelope 7"),
         "iso_c7c6_81x162mm": qsTr("CEnvelope 7c6"),
         "iso_c8_57x81mm": qsTr("CEnvelope 8"),
         "iso_c9_40x57mm": qsTr("CEnvelope 9"),
         "iso_dl_110x220mm": qsTr("Envelope DL"),
         "iso_id-1_53.98x85.6mm": qsTr("Id-1"),
         "iso_id-3_88x125mm": qsTr("Id-3"),
         "iso_ra0_860x1220mm": qsTr("ISO RA0"),
         "iso_ra1_610x860mm": qsTr("ISO RA1"),
         "iso_ra2_430x610mm": qsTr("ISO RA2"),
         "iso_ra3_305x430mm": qsTr("ISO RA3"),
         "iso_ra4_215x305mm": qsTr("ISO RA4"),
         "iso_sra0_900x1280mm": qsTr("ISO SRA0"),
         "iso_sra1_640x900mm": qsTr("ISO SRA1"),
         "iso_sra2_450x640mm": qsTr("ISO SRA2"),
         "iso_sra3_320x450mm": qsTr("ISO SRA3"),
         "iso_sra4_225x320mm": qsTr("ISO SRA4"),
         "jis_b0_1030x1456mm": qsTr("JIS B0"),
         "jis_b10_32x45mm": qsTr("JIS B10"),
         "jis_b1_728x1030mm": qsTr("JIS B1"),
         "jis_b2_515x728mm": qsTr("JIS B2"),
         "jis_b3_364x515mm": qsTr("JIS B3"),
         "jis_b4_257x364mm": qsTr("JIS B4"),
         "jis_b5_182x257mm": qsTr("JIS B5"),
         "jis_b6_128x182mm": qsTr("JIS B6"),
         "jis_b7_91x128mm": qsTr("JIS B7"),
         "jis_b8_64x91mm": qsTr("JIS B8"),
         "jis_b9_45x64mm": qsTr("JIS B9"),
         "jis_exec_216x330mm": qsTr("JIS Executive"),
         "jpn_chou2_111.1x146mm": qsTr("Envelope Chou 2"),
         "jpn_chou3_120x235mm": qsTr("Envelope Chou 3"),
         "jpn_chou40_90x225mm": qsTr("Envelope Chou 40"),
         "jpn_chou4_90x205mm": qsTr("Envelope Chou 4"),
         "jpn_hagaki_100x148mm": qsTr("Hagaki"),
         "jpn_kahu_240x322.1mm": qsTr("Envelope Kahu"),
         "jpn_kaku1_270x382mm": qsTr("270 x 382mm"),
         "jpn_kaku2_240x332mm": qsTr("Envelope Kahu 2"),
         "jpn_kaku3_216x277mm": qsTr("216 x 277mm"),
         "jpn_kaku4_197x267mm": qsTr("197 x 267mm"),
         "jpn_kaku5_190x240mm": qsTr("190 x 240mm"),
         "jpn_kaku7_142x205mm": qsTr("142 x 205mm"),
         "jpn_kaku8_119x197mm": qsTr("119 x 197mm"),
         "jpn_oufuku_148x200mm": qsTr("Oufuku Reply Postcard"),
         "jpn_you4_105x235mm": qsTr("Envelope You 4"),
         "na_10x11_10x11in": qsTr("10 x 11″"),
         "na_10x13_10x13in": qsTr("10 x 13″"),
         "na_10x14_10x14in": qsTr("10 x 14″"),
         "na_10x15_10x15in": qsTr("10 x 15″"),
         "na_11x12_11x12in": qsTr("11 x 12″"),
         "na_11x15_11x15in": qsTr("11 x 15″"),
         "na_12x19_12x19in": qsTr("12 x 19″"),
         "na_5x7_5x7in": qsTr("5 x 7″"),
         "na_6x9_6x9in": qsTr("6 x 9″"),
         "na_7x9_7x9in": qsTr("7 x 9″"),
         "na_9x11_9x11in": qsTr("9 x 11″"),
         "na_a2_4.375x5.75in": qsTr("Envelope A2"),
         "na_arch-a_9x12in": qsTr("9 x 12″"),
         "na_arch-b_12x18in": qsTr("12 x 18″"),
         "na_arch-c_18x24in": qsTr("18 x 24″"),
         "na_arch-d_24x36in": qsTr("24 x 36″"),
         "na_arch-e2_26x38in": qsTr("26 x 38″"),
         "na_arch-e3_27x39in": qsTr("27 x 39″"),
         "na_arch-e_36x48in": qsTr("36 x 48″"),
         "na_b-plus_12x19.17in": qsTr("12 x 19.17″"),
         "na_c5_6.5x9.5in": qsTr("Envelope C5"),
         "na_c_17x22in": qsTr("17 x 22″"),
         "na_d_22x34in": qsTr("22 x 34″"),
         "na_e_34x44in": qsTr("34 x 44″"),
         "na_edp_11x14in": qsTr("11 x 14″"),
         "na_eur-edp_12x14in": qsTr("12 x 14″"),
         "na_executive_7.25x10.5in": qsTr("Executive"),
         "na_f_44x68in": qsTr("44 x 68″"),
         "na_fanfold-eur_8.5x12in": qsTr("European Fanfold"),
         "na_fanfold-us_11x14.875in": qsTr("US Fanfold"),
         "na_foolscap_8.5x13in": qsTr("Foolscap"),
         "na_govt-legal_8x13in": qsTr("8 x 13″"),
         "na_govt-letter_8x10in": qsTr("8 x 10″"),
         "na_index-3x5_3x5in": qsTr("3 x 5″"),
         "na_index-4x6-ext_6x8in": qsTr("6 x 8″"),
         "na_index-4x6_4x6in": qsTr("4 x 6″"),
         "na_index-5x8_5x8in": qsTr("5 x 8″"),
         "na_invoice_5.5x8.5in": qsTr("Statement"),
         "na_ledger_11x17in": qsTr("11 x 17″"),
         "na_legal-extra_9.5x15in": qsTr("US Legal (Extra)"),
         "na_legal_8.5x14in": qsTr("US Legal"),
         "na_letter-extra_9.5x12in": qsTr("US Letter (Extra)"),
         "na_letter-plus_8.5x12.69in": qsTr("US Letter (Plus)"),
         "na_letter_8.5x11in": qsTr("US Letter"),
         "na_monarch_3.875x7.5in": qsTr("Envelope Monarch"),
         "na_number-10_4.125x9.5in": qsTr("Envelope #10"),
         "na_number-11_4.5x10.375in": qsTr("Envelope #11"),
         "na_number-12_4.75x11in": qsTr("Envelope #12"),
         "na_number-14_5x11.5in": qsTr("Envelope #14"),
         "na_number-9_3.875x8.875in": qsTr("Envelope #9"),
         "na_oficio_8.5x13.4in": qsTr("8.5 x 13.4″"),
         "na_personal_3.625x6.5in": qsTr("Envelope Personal"),
         "na_quarto_8.5x10.83in": qsTr("Quarto"),
         "na_super-a_8.94x14in": qsTr("8.94 x 14″"),
         "na_super-b_13x19in": qsTr("13 x 19″"),
         "na_wide-format_30x42in": qsTr("30 x 42″"),
         "oe_12x16_12x16in": qsTr("12 x 16″"),
         "oe_14x17_14x17in": qsTr("14 x 17″"),
         "oe_18x22_18x22in": qsTr("18 x 22″"),
         "oe_a2plus_17x24in": qsTr("17 x 24″"),
         "oe_business-card_2x3.5in": qsTr("2 x 3.5″"),
         "oe_photo-10r_10x12in": qsTr("10 x 12″"),
         "oe_photo-20r_20x24in": qsTr("20 x 24″"),
         "oe_photo-l_3.5x5in": qsTr("3.5 x 5″"),
         "oe_photo-s10r_10x15in": qsTr("10 x 15″"),
         "oe_square-photo_4x4in": qsTr("4 x 4″"),
         "oe_square-photo_5x5in": qsTr("5 x 5″"),
         "om_16k_184x260mm": qsTr("184 x 260mm"),
         "om_16k_195x270mm": qsTr("195 x 270mm"),
         "om_business-card_55x85mm": qsTr("55 x 85mm"),
         "om_business-card_55x91mm": qsTr("55 x 91mm"),
         "om_card_54x86mm": qsTr("54 x 86mm"),
         "om_dai-pa-kai_275x395mm": qsTr("275 x 395mm"),
         "om_dsc-photo_89x119mm": qsTr("89 x 119mm"),
         "om_folio-sp_215x315mm": qsTr("Folio"),
         "om_folio_210x330mm": qsTr("Folio (Special)"),
         "om_invite_220x220mm": qsTr("Envelope Invitation"),
         "om_italian_110x230mm": qsTr("Envelope Italian"),
         "om_juuro-ku-kai_198x275mm": qsTr("198 x 275mm"),
         "om_large-photo_200x300": qsTr("200 x 300"),
         "om_medium-photo_130x180mm": qsTr("130 x 180mm"),
         "om_pa-kai_267x389mm": qsTr("267 x 389mm"),
         "om_postfix_114x229mm": qsTr("Envelope Postfix"),
         "om_small-photo_100x150mm": qsTr("100 x 150mm"),
         "om_square-photo_89x89mm": qsTr("89 x 89mm"),
         "om_wide-photo_100x200mm": qsTr("100 x 200mm"),
         "prc_10_324x458mm": qsTr("Envelope Chinese #10"),
         "prc_16k_146x215mm": qsTr("Chinese 16k"),
         "prc_1_102x165mm": qsTr("Envelope Chinese #1"),
         "prc_2_102x176mm": qsTr("Envelope Chinese #2"),
         "prc_32k_97x151mm": qsTr("Chinese 32k"),
         "prc_3_125x176mm": qsTr("Envelope Chinese #3"),
         "prc_4_110x208mm": qsTr("Envelope Chinese #4"),
         "prc_5_110x220mm": qsTr("Envelope Chinese #5"),
         "prc_6_120x320mm": qsTr("Envelope Chinese #6"),
         "prc_7_160x230mm": qsTr("Envelope Chinese #7"),
         "prc_8_120x309mm": qsTr("Envelope Chinese #8"),
         "roc_16k_7.75x10.75in": qsTr("ROC 16k"),
         "roc_8k_10.75x15.5in": qsTr("ROC 8k")}

var mediaType =
        {"aluminum": qsTr("Aluminum"),
         "auto": qsTr("Automatic"),
         "back-print-film": qsTr("Back Print Film"),
         "cardboard": qsTr("Cardboard"),
         "cardstock": qsTr("Cardstock"),
         "cd": qsTr("CD"),
         "continuous": qsTr("Continuous"),
         "continuous-long": qsTr("Continuous Long"),
         "continuous-short": qsTr("Continuous Short"),
         "corrugated-board": qsTr("Corrugated Board"),
         "disc": qsTr("Optical Disc"),
         "disc-glossy": qsTr("Glossy Optical Disc"),
         "disc-high-gloss": qsTr("High Gloss Optical Disc"),
         "disc-matte": qsTr("Matte Optical Disc"),
         "disc-satin": qsTr("Satin Optical Disc"),
         "disc-semi-gloss": qsTr("Semi-Gloss Optical Disc"),
         "double-wall": qsTr("Double Wall"),
         "dry-film": qsTr("Dry Film"),
         "dvd": qsTr("DVD"),
         "embossing-foil": qsTr("Embossing Foil"),
         "end-board": qsTr("End Board"),
         "envelope": qsTr("Envelope"),
         "envelope-archival": qsTr("Archival Envelope"),
         "envelope-bond": qsTr("Bond Envelope"),
         "envelope-coated": qsTr("Coated Envelope"),
         "envelope-cotton": qsTr("Cotton Envelope"),
         "envelope-fine": qsTr("Fine Envelope"),
         "envelope-heavyweight": qsTr("Heavyweight Envelope"),
         "envelope-inkjet": qsTr("Inkjet Envelope"),
         "envelope-lightweight": qsTr("Lightweight Envelope"),
         "envelope-plain": qsTr("Plain Envelope"),
         "envelope-preprinted": qsTr("Preprinted Envelope"),
         "envelope-window": qsTr("Windowed Envelope"),
         "fabric": qsTr("Fabric"),
         "fabric-archival": qsTr("Archival Fabric"),
         "fabric-glossy": qsTr("Glossy Fabric"),
         "fabric-high-gloss": qsTr("High Gloss Fabric"),
         "fabric-matte": qsTr("Matte Fabric"),
         "fabric-semi-gloss": qsTr("Semi-Gloss Fabric"),
         "fabric-waterproof": qsTr("Waterproof Fabric"),
         "film": qsTr("Film"),
         "flexo-base": qsTr("Flexo Base"),
         "flexo-photo-polymer": qsTr("Flexo Photo Polymer"),
         "flute": qsTr("Flute"),
         "foil": qsTr("Foil"),
         "full-cut-tabs": qsTr("Full Cut Tabs"),
         "glass": qsTr("Glass"),
         "glass-colored": qsTr("Glass Colored"),
         "glass-opaque": qsTr("Glass Opaque"),
         "glass-surfaced": qsTr("Glass Surfaced"),
         "glass-textured": qsTr("Glass Textured"),
         "gravure-cylinder": qsTr("Gravure Cylinder"),
         "image-setter-paper": qsTr("Image Setter Paper"),
         "imaging-cylinder": qsTr("Imaging Cylinder"),
         "labels": qsTr("Labels"),
         "labels-colored": qsTr("Colored Labels"),
         "labels-glossy": qsTr("Glossy Labels"),
         "labels-high-gloss": qsTr("High Gloss Labels"),
         "labels-inkjet": qsTr("Inkjet Labels"),
         "labels-matte": qsTr("Matte Labels"),
         "labels-permanent": qsTr("Permanent Labels"),
         "labels-satin": qsTr("Satin Labels"),
         "labels-security": qsTr("Security Labels"),
         "labels-semi-gloss": qsTr("Semi-Gloss Labels"),
         "laminating-foil": qsTr("Laminating Foil"),
         "letterhead": qsTr("Letterhead"),
         "metal": qsTr("Metal"),
         "metal-glossy": qsTr("Metal Glossy"),
         "metal-high-gloss": qsTr("Metal High Gloss"),
         "metal-matte": qsTr("Metal Matte"),
         "metal-satin": qsTr("Metal Satin"),
         "metal-semi-gloss": qsTr("Metal Semi Gloss"),
         "mounting-tape": qsTr("Mounting Tape"),
         "multi-layer": qsTr("Multi Layer"),
         "multi-part-form": qsTr("Multi Part Form"),
         "other": qsTr("Other"),
         "paper": qsTr("Paper"),
         "photographic": qsTr("Photo Paper"),
         "photographic-archival": qsTr("Photographic Archival"),
         "photographic-film": qsTr("Photo Film"),
         "photographic-glossy": qsTr("Glossy Photo Paper"),
         "photographic-high-gloss": qsTr("High Gloss Photo Paper"),
         "photographic-matte": qsTr("Matte Photo Paper"),
         "photographic-satin": qsTr("Satin Photo Paper"),
         "photographic-semi-gloss": qsTr("Semi-Gloss Photo Paper"),
         "plastic": qsTr("Plastic"),
         "plastic-archival": qsTr("Plastic Archival"),
         "plastic-colored": qsTr("Plastic Colored"),
         "plastic-glossy": qsTr("Plastic Glossy"),
         "plastic-high-gloss": qsTr("Plastic High Gloss"),
         "plastic-matte": qsTr("Plastic Matte"),
         "plastic-satin": qsTr("Plastic Satin"),
         "plastic-semi-gloss": qsTr("Plastic Semi Gloss"),
         "plate": qsTr("Plate"),
         "polyester": qsTr("Polyester"),
         "pre-cut-tabs": qsTr("Pre Cut Tabs"),
         "roll": qsTr("Roll"),
         "screen": qsTr("Screen"),
         "screen-paged": qsTr("Screen Paged"),
         "self-adhesive": qsTr("Self Adhesive"),
         "self-adhesive-film": qsTr("Self Adhesive Film"),
         "shrink-foil": qsTr("Shrink Foil"),
         "single-face": qsTr("Single Face"),
         "single-wall": qsTr("Single Wall"),
         "sleeve": qsTr("Sleeve"),
         "stationery": qsTr("Stationery"),
         "stationery-archival": qsTr("Stationery Archival"),
         "stationery-coated": qsTr("Coated Paper"),
         "stationery-cotton": qsTr("Stationery Cotton"),
         "stationery-fine": qsTr("Vellum Paper"),
         "stationery-heavyweight": qsTr("Heavyweight Paper"),
         "stationery-heavyweight-coated": qsTr("Stationery Heavyweight Coated"),
         "stationery-inkjet": qsTr("Stationery Inkjet Paper"),
         "stationery-letterhead": qsTr("Letterhead"),
         "stationery-lightweight": qsTr("Lightweight Paper"),
         "stationery-preprinted": qsTr("Preprinted Paper"),
         "stationery-prepunched": qsTr("Punched Paper"),
         "tab-stock": qsTr("Tab Stock"),
         "tractor": qsTr("Tractor"),
         "transfer": qsTr("Transfer"),
         "transparency": qsTr("Transparency"),
         "triple-wall": qsTr("Triple Wall"),
         "wet-film": qsTr("Wet Film")}

var printerStateReasons =
        {"alert-removal-of-binary-change-entry": qsTr("Old Alerts Have Been Removed"),
         "bander-added": qsTr("Bander Added"),
         "bander-almost-empty": qsTr("Bander Almost Empty"),
         "bander-almost-full": qsTr("Bander Almost Full"),
         "bander-at-limit": qsTr("Bander At Limit"),
         "bander-closed": qsTr("Bander Closed"),
         "bander-configuration-change": qsTr("Bander Configuration Change"),
         "bander-cover-closed": qsTr("Bander Cover Closed"),
         "bander-cover-open": qsTr("Bander Cover Open"),
         "bander-empty": qsTr("Bander Empty"),
         "bander-full": qsTr("Bander Full"),
         "bander-interlock-closed": qsTr("Bander Interlock Closed"),
         "bander-interlock-open": qsTr("Bander Interlock Open"),
         "bander-jam": qsTr("Bander Jam"),
         "bander-life-almost-over": qsTr("Bander Life Almost Over"),
         "bander-life-over": qsTr("Bander Life Over"),
         "bander-memory-exhausted": qsTr("Bander Memory Exhausted"),
         "bander-missing": qsTr("Bander Missing"),
         "bander-motor-failure": qsTr("Bander Motor Failure"),
         "bander-near-limit": qsTr("Bander Near Limit"),
         "bander-offline": qsTr("Bander Offline"),
         "bander-opened": qsTr("Bander Opened"),
         "bander-over-temperature": qsTr("Bander Over Temperature"),
         "bander-power-saver": qsTr("Bander Power Saver"),
         "bander-recoverable-failure": qsTr("Bander Recoverable Failure"),
         "bander-recoverable-storage": qsTr("Bander Recoverable Storage"),
         "bander-removed": qsTr("Bander Removed"),
         "bander-resource-added": qsTr("Bander Resource Added"),
         "bander-resource-removed": qsTr("Bander Resource Removed"),
         "bander-thermistor-failure": qsTr("Bander Thermistor Failure"),
         "bander-timing-failure": qsTr("Bander Timing Failure"),
         "bander-turned-off": qsTr("Bander Turned Off"),
         "bander-turned-on": qsTr("Bander Turned On"),
         "bander-under-temperature": qsTr("Bander Under Temperature"),
         "bander-unrecoverable-failure": qsTr("Bander Unrecoverable Failure"),
         "bander-unrecoverable-storage-error": qsTr("Bander Unrecoverable Storage Error"),
         "bander-warming-up": qsTr("Bander Warming Up"),
         "binder-added": qsTr("Binder Added"),
         "binder-almost-empty": qsTr("Binder Almost Empty"),
         "binder-almost-full": qsTr("Binder Almost Full"),
         "binder-at-limit": qsTr("Binder At Limit"),
         "binder-closed": qsTr("Binder Closed"),
         "binder-configuration-change": qsTr("Binder Configuration Change"),
         "binder-cover-closed": qsTr("Binder Cover Closed"),
         "binder-cover-open": qsTr("Binder Cover Open"),
         "binder-empty": qsTr("Binder Empty"),
         "binder-full": qsTr("Binder Full"),
         "binder-interlock-closed": qsTr("Binder Interlock Closed"),
         "binder-interlock-open": qsTr("Binder Interlock Open"),
         "binder-jam": qsTr("Binder Jam"),
         "binder-life-almost-over": qsTr("Binder Life Almost Over"),
         "binder-life-over": qsTr("Binder Life Over"),
         "binder-memory-exhausted": qsTr("Binder Memory Exhausted"),
         "binder-missing": qsTr("Binder Missing"),
         "binder-motor-failure": qsTr("Binder Motor Failure"),
         "binder-near-limit": qsTr("Binder Near Limit"),
         "binder-offline": qsTr("Binder Offline"),
         "binder-opened": qsTr("Binder Opened"),
         "binder-over-temperature": qsTr("Binder Over Temperature"),
         "binder-power-saver": qsTr("Binder Power Saver"),
         "binder-recoverable-failure": qsTr("Binder Recoverable Failure"),
         "binder-recoverable-storage": qsTr("Binder Recoverable Storage"),
         "binder-removed": qsTr("Binder Removed"),
         "binder-resource-added": qsTr("Binder Resource Added"),
         "binder-resource-removed": qsTr("Binder Resource Removed"),
         "binder-thermistor-failure": qsTr("Binder Thermistor Failure"),
         "binder-timing-failure": qsTr("Binder Timing Failure"),
         "binder-turned-off": qsTr("Binder Turned Off"),
         "binder-turned-on": qsTr("Binder Turned On"),
         "binder-under-temperature": qsTr("Binder Under Temperature"),
         "binder-unrecoverable-failure": qsTr("Binder Unrecoverable Failure"),
         "binder-unrecoverable-storage-error": qsTr("Binder Unrecoverable Storage Error"),
         "binder-warming-up": qsTr("Binder Warming Up"),
         "camera-failure": qsTr("Camera Failure"),
         "chamber-cooling": qsTr("Chamber Cooling"),
         "chamber-failure": qsTr("Chamber Failure"),
         "chamber-heating": qsTr("Chamber Heating"),
         "chamber-temperature-high": qsTr("Chamber Temperature High"),
         "chamber-temperature-low": qsTr("Chamber Temperature Low"),
         "cleaner-life-almost-over": qsTr("Cleaner Life Almost Over"),
         "cleaner-life-over": qsTr("Cleaner Life Over"),
         "configuration-change": qsTr("Configuration Change"),
         "connecting-to-device": qsTr("Connecting To Device"),
         "cover-open": qsTr("Cover Open"),
         "deactivated": qsTr("Deactivated"),
         "developer-empty": qsTr("Developer Empty"),
         "developer-low": qsTr("Developer Low"),
         "die-cutter-added": qsTr("Die Cutter Added"),
         "die-cutter-almost-empty": qsTr("Die Cutter Almost Empty"),
         "die-cutter-almost-full": qsTr("Die Cutter Almost Full"),
         "die-cutter-at-limit": qsTr("Die Cutter At Limit"),
         "die-cutter-closed": qsTr("Die Cutter Closed"),
         "die-cutter-configuration-change": qsTr("Die Cutter Configuration Change"),
         "die-cutter-cover-closed": qsTr("Die Cutter Cover Closed"),
         "die-cutter-cover-open": qsTr("Die Cutter Cover Open"),
         "die-cutter-empty": qsTr("Die Cutter Empty"),
         "die-cutter-full": qsTr("Die Cutter Full"),
         "die-cutter-interlock-closed": qsTr("Die Cutter Interlock Closed"),
         "die-cutter-interlock-open": qsTr("Die Cutter Interlock Open"),
         "die-cutter-jam": qsTr("Die Cutter Jam"),
         "die-cutter-life-almost-over": qsTr("Die Cutter Life Almost Over"),
         "die-cutter-life-over": qsTr("Die Cutter Life Over"),
         "die-cutter-memory-exhausted": qsTr("Die Cutter Memory Exhausted"),
         "die-cutter-missing": qsTr("Die Cutter Missing"),
         "die-cutter-motor-failure": qsTr("Die Cutter Motor Failure"),
         "die-cutter-near-limit": qsTr("Die Cutter Near Limit"),
         "die-cutter-offline": qsTr("Die Cutter Offline"),
         "die-cutter-opened": qsTr("Die Cutter Opened"),
         "die-cutter-over-temperature": qsTr("Die Cutter Over Temperature"),
         "die-cutter-power-saver": qsTr("Die Cutter Power Saver"),
         "die-cutter-recoverable-failure": qsTr("Die Cutter Recoverable Failure"),
         "die-cutter-recoverable-storage": qsTr("Die Cutter Recoverable Storage"),
         "die-cutter-removed": qsTr("Die Cutter Removed"),
         "die-cutter-resource-added": qsTr("Die Cutter Resource Added"),
         "die-cutter-resource-removed": qsTr("Die Cutter Resource Removed"),
         "die-cutter-thermistor-failure": qsTr("Die Cutter Thermistor Failure"),
         "die-cutter-timing-failure": qsTr("Die Cutter Timing Failure"),
         "die-cutter-turned-off": qsTr("Die Cutter Turned Off"),
         "die-cutter-turned-on": qsTr("Die Cutter Turned On"),
         "die-cutter-under-temperature": qsTr("Die Cutter Under Temperature"),
         "die-cutter-unrecoverable-failure": qsTr("Die Cutter Unrecoverable Failure"),
         "die-cutter-unrecoverable-storage-error": qsTr("Die Cutter Unrecoverable Storage Error"),
         "die-cutter-warming-up": qsTr("Die Cutter Warming Up"),
         "door-open": qsTr("Door Open"),
         "extruder-cooling": qsTr("Extruder Cooling"),
         "extruder-failure": qsTr("Extruder Failure"),
         "extruder-heating": qsTr("Extruder Heating"),
         "extruder-jam": qsTr("Extruder Jam"),
         "extruder-temperature-high": qsTr("Extruder Temperature High"),
         "extruder-temperature-low": qsTr("Extruder Temperature Low"),
         "fan-failure": qsTr("Fan Failure"),
         "fax-modem-life-almost-over": qsTr("Fax Modem Life Almost Over"),
         "fax-modem-life-over": qsTr("Fax Modem Life Over"),
         "fax-modem-missing": qsTr("Fax Modem Missing"),
         "fax-modem-turned-off": qsTr("Fax Modem Turned Off"),
         "fax-modem-turned-on": qsTr("Fax Modem Turned On"),
         "folder-added": qsTr("Folder Added"),
         "folder-almost-empty": qsTr("Folder Almost Empty"),
         "folder-almost-full": qsTr("Folder Almost Full"),
         "folder-at-limit": qsTr("Folder At Limit"),
         "folder-closed": qsTr("Folder Closed"),
         "folder-configuration-change": qsTr("Folder Configuration Change"),
         "folder-cover-closed": qsTr("Folder Cover Closed"),
         "folder-cover-open": qsTr("Folder Cover Open"),
         "folder-empty": qsTr("Folder Empty"),
         "folder-full": qsTr("Folder Full"),
         "folder-interlock-closed": qsTr("Folder Interlock Closed"),
         "folder-interlock-open": qsTr("Folder Interlock Open"),
         "folder-jam": qsTr("Folder Jam"),
         "folder-life-almost-over": qsTr("Folder Life Almost Over"),
         "folder-life-over": qsTr("Folder Life Over"),
         "folder-memory-exhausted": qsTr("Folder Memory Exhausted"),
         "folder-missing": qsTr("Folder Missing"),
         "folder-motor-failure": qsTr("Folder Motor Failure"),
         "folder-near-limit": qsTr("Folder Near Limit"),
         "folder-offline": qsTr("Folder Offline"),
         "folder-opened": qsTr("Folder Opened"),
         "folder-over-temperature": qsTr("Folder Over Temperature"),
         "folder-power-saver": qsTr("Folder Power Saver"),
         "folder-recoverable-failure": qsTr("Folder Recoverable Failure"),
         "folder-recoverable-storage": qsTr("Folder Recoverable Storage"),
         "folder-removed": qsTr("Folder Removed"),
         "folder-resource-added": qsTr("Folder Resource Added"),
         "folder-resource-removed": qsTr("Folder Resource Removed"),
         "folder-thermistor-failure": qsTr("Folder Thermistor Failure"),
         "folder-timing-failure": qsTr("Folder Timing Failure"),
         "folder-turned-off": qsTr("Folder Turned Off"),
         "folder-turned-on": qsTr("Folder Turned On"),
         "folder-under-temperature": qsTr("Folder Under Temperature"),
         "folder-unrecoverable-failure": qsTr("Folder Unrecoverable Failure"),
         "folder-unrecoverable-storage-error": qsTr("Folder Unrecoverable Storage Error"),
         "folder-warming-up": qsTr("Folder Warming Up"),
         "fuser-over-temp": qsTr("Fuser temperature high"),
         "fuser-under-temp": qsTr("Fuser temperature low"),
         "hold-new-jobs": qsTr("Hold New Jobs"),
         "identify-printer-requested": qsTr("Identify Printer"),
         "imprinter-added": qsTr("Imprinter Added"),
         "imprinter-almost-empty": qsTr("Imprinter Almost Empty"),
         "imprinter-almost-full": qsTr("Imprinter Almost Full"),
         "imprinter-at-limit": qsTr("Imprinter At Limit"),
         "imprinter-closed": qsTr("Imprinter Closed"),
         "imprinter-configuration-change": qsTr("Imprinter Configuration Change"),
         "imprinter-cover-closed": qsTr("Imprinter Cover Closed"),
         "imprinter-cover-open": qsTr("Imprinter Cover Open"),
         "imprinter-empty": qsTr("Imprinter Empty"),
         "imprinter-full": qsTr("Imprinter Full"),
         "imprinter-interlock-closed": qsTr("Imprinter Interlock Closed"),
         "imprinter-interlock-open": qsTr("Imprinter Interlock Open"),
         "imprinter-jam": qsTr("Imprinter Jam"),
         "imprinter-life-almost-over": qsTr("Imprinter Life Almost Over"),
         "imprinter-life-over": qsTr("Imprinter Life Over"),
         "imprinter-memory-exhausted": qsTr("Imprinter Memory Exhausted"),
         "imprinter-missing": qsTr("Imprinter Missing"),
         "imprinter-motor-failure": qsTr("Imprinter Motor Failure"),
         "imprinter-near-limit": qsTr("Imprinter Near Limit"),
         "imprinter-offline": qsTr("Imprinter Offline"),
         "imprinter-opened": qsTr("Imprinter Opened"),
         "imprinter-over-temperature": qsTr("Imprinter Over Temperature"),
         "imprinter-power-saver": qsTr("Imprinter Power Saver"),
         "imprinter-recoverable-failure": qsTr("Imprinter Recoverable Failure"),
         "imprinter-recoverable-storage": qsTr("Imprinter Recoverable Storage"),
         "imprinter-removed": qsTr("Imprinter Removed"),
         "imprinter-resource-added": qsTr("Imprinter Resource Added"),
         "imprinter-resource-removed": qsTr("Imprinter Resource Removed"),
         "imprinter-thermistor-failure": qsTr("Imprinter Thermistor Failure"),
         "imprinter-timing-failure": qsTr("Imprinter Timing Failure"),
         "imprinter-turned-off": qsTr("Imprinter Turned Off"),
         "imprinter-turned-on": qsTr("Imprinter Turned On"),
         "imprinter-under-temperature": qsTr("Imprinter Under Temperature"),
         "imprinter-unrecoverable-failure": qsTr("Imprinter Unrecoverable Failure"),
         "imprinter-unrecoverable-storage-error": qsTr("Imprinter Unrecoverable Storage Error"),
         "imprinter-warming-up": qsTr("Imprinter Warming Up"),
         "input-cannot-feed-size-selected": qsTr("Input Cannot Feed Size Selected"),
         "input-manual-input-request": qsTr("Input Manual Input Request"),
         "input-media-color-change": qsTr("Input Media Color Change"),
         "input-media-form-parts-change": qsTr("Input Media Form Parts Change"),
         "input-media-size-change": qsTr("Input Media Size Change"),
         "input-media-tray-failure": qsTr("Input Media Tray Failure"),
         "input-media-tray-feed-error": qsTr("Input Media Tray Feed Error"),
         "input-media-tray-jam": qsTr("Input Media Tray Jam"),
         "input-media-type-change": qsTr("Input Media Type Change"),
         "input-media-weight-change": qsTr("Input Media Weight Change"),
         "input-pick-roller-failure": qsTr("Input Pick Roller Failure"),
         "input-pick-roller-life-over": qsTr("Input Pick Roller Life Over"),
         "input-pick-roller-life-warn": qsTr("Input Pick Roller Life Warn"),
         "input-pick-roller-missing": qsTr("Input Pick Roller Missing"),
         "input-tray-elevation-failure": qsTr("Input Tray Elevation Failure"),
         "input-tray-missing": qsTr("Paper tray is missing"),
         "input-tray-position-failure": qsTr("Input Tray Position Failure"),
         "inserter-added": qsTr("Inserter Added"),
         "inserter-almost-empty": qsTr("Inserter Almost Empty"),
         "inserter-almost-full": qsTr("Inserter Almost Full"),
         "inserter-at-limit": qsTr("Inserter At Limit"),
         "inserter-closed": qsTr("Inserter Closed"),
         "inserter-configuration-change": qsTr("Inserter Configuration Change"),
         "inserter-cover-closed": qsTr("Inserter Cover Closed"),
         "inserter-cover-open": qsTr("Inserter Cover Open"),
         "inserter-empty": qsTr("Inserter Empty"),
         "inserter-full": qsTr("Inserter Full"),
         "inserter-interlock-closed": qsTr("Inserter Interlock Closed"),
         "inserter-interlock-open": qsTr("Inserter Interlock Open"),
         "inserter-jam": qsTr("Inserter Jam"),
         "inserter-life-almost-over": qsTr("Inserter Life Almost Over"),
         "inserter-life-over": qsTr("Inserter Life Over"),
         "inserter-memory-exhausted": qsTr("Inserter Memory Exhausted"),
         "inserter-missing": qsTr("Inserter Missing"),
         "inserter-motor-failure": qsTr("Inserter Motor Failure"),
         "inserter-near-limit": qsTr("Inserter Near Limit"),
         "inserter-offline": qsTr("Inserter Offline"),
         "inserter-opened": qsTr("Inserter Opened"),
         "inserter-over-temperature": qsTr("Inserter Over Temperature"),
         "inserter-power-saver": qsTr("Inserter Power Saver"),
         "inserter-recoverable-failure": qsTr("Inserter Recoverable Failure"),
         "inserter-recoverable-storage": qsTr("Inserter Recoverable Storage"),
         "inserter-removed": qsTr("Inserter Removed"),
         "inserter-resource-added": qsTr("Inserter Resource Added"),
         "inserter-resource-removed": qsTr("Inserter Resource Removed"),
         "inserter-thermistor-failure": qsTr("Inserter Thermistor Failure"),
         "inserter-timing-failure": qsTr("Inserter Timing Failure"),
         "inserter-turned-off": qsTr("Inserter Turned Off"),
         "inserter-turned-on": qsTr("Inserter Turned On"),
         "inserter-under-temperature": qsTr("Inserter Under Temperature"),
         "inserter-unrecoverable-failure": qsTr("Inserter Unrecoverable Failure"),
         "inserter-unrecoverable-storage-error": qsTr("Inserter Unrecoverable Storage Error"),
         "inserter-warming-up": qsTr("Inserter Warming Up"),
         "interlock-closed": qsTr("Interlock Closed"),
         "interlock-open": qsTr("Interlock Open"),
         "interpreter-cartridge-added": qsTr("Interpreter Cartridge Added"),
         "interpreter-cartridge-deleted": qsTr("Interpreter Cartridge Removed"),
         "interpreter-complex-page-encountered": qsTr("Interpreter Complex Page Encountered"),
         "interpreter-memory-decrease": qsTr("Interpreter Memory Decrease"),
         "interpreter-memory-increase": qsTr("Interpreter Memory Increase"),
         "interpreter-resource-added": qsTr("Interpreter Resource Added"),
         "interpreter-resource-deleted": qsTr("Interpreter Resource Deleted"),
         "interpreter-resource-unavailable": qsTr("Printer resource unavailable"),
         "lamp-at-eol": qsTr("Lamp At End of Life"),
         "lamp-failure": qsTr("Lamp Failure"),
         "lamp-near-eol": qsTr("Lamp Near End of Life"),
         "laser-at-eol": qsTr("Laser At End of Life"),
         "laser-failure": qsTr("Laser Failure"),
         "laser-near-eol": qsTr("Laser Near End of Life"),
         "make-envelope-added": qsTr("Envelope Maker Added"),
         "make-envelope-almost-empty": qsTr("Envelope Maker Almost Empty"),
         "make-envelope-almost-full": qsTr("Envelope Maker Almost Full"),
         "make-envelope-at-limit": qsTr("Envelope Maker At Limit"),
         "make-envelope-closed": qsTr("Envelope Maker Closed"),
         "make-envelope-configuration-change": qsTr("Envelope Maker Configuration Change"),
         "make-envelope-cover-closed": qsTr("Envelope Maker Cover Closed"),
         "make-envelope-cover-open": qsTr("Envelope Maker Cover Open"),
         "make-envelope-empty": qsTr("Envelope Maker Empty"),
         "make-envelope-full": qsTr("Envelope Maker Full"),
         "make-envelope-interlock-closed": qsTr("Envelope Maker Interlock Closed"),
         "make-envelope-interlock-open": qsTr("Envelope Maker Interlock Open"),
         "make-envelope-jam": qsTr("Envelope Maker Jam"),
         "make-envelope-life-almost-over": qsTr("Envelope Maker Life Almost Over"),
         "make-envelope-life-over": qsTr("Envelope Maker Life Over"),
         "make-envelope-memory-exhausted": qsTr("Envelope Maker Memory Exhausted"),
         "make-envelope-missing": qsTr("Envelope Maker Missing"),
         "make-envelope-motor-failure": qsTr("Envelope Maker Motor Failure"),
         "make-envelope-near-limit": qsTr("Envelope Maker Near Limit"),
         "make-envelope-offline": qsTr("Envelope Maker Offline"),
         "make-envelope-opened": qsTr("Envelope Maker Opened"),
         "make-envelope-over-temperature": qsTr("Envelope Maker Over Temperature"),
         "make-envelope-power-saver": qsTr("Envelope Maker Power Saver"),
         "make-envelope-recoverable-failure": qsTr("Envelope Maker Recoverable Failure"),
         "make-envelope-recoverable-storage": qsTr("Envelope Maker Recoverable Storage"),
         "make-envelope-removed": qsTr("Envelope Maker Removed"),
         "make-envelope-resource-added": qsTr("Envelope Maker Resource Added"),
         "make-envelope-resource-removed": qsTr("Envelope Maker Resource Removed"),
         "make-envelope-thermistor-failure": qsTr("Envelope Maker Thermistor Failure"),
         "make-envelope-timing-failure": qsTr("Envelope Maker Timing Failure"),
         "make-envelope-turned-off": qsTr("Envelope Maker Turned Off"),
         "make-envelope-turned-on": qsTr("Envelope Maker Turned On"),
         "make-envelope-under-temperature": qsTr("Envelope Maker Under Temperature"),
         "make-envelope-unrecoverable-failure": qsTr("Envelope Maker Unrecoverable Failure"),
         "make-envelope-unrecoverable-storage-error": qsTr("Envelope Maker Unrecoverable Storage Error"),
         "make-envelope-warming-up": qsTr("Envelope Maker Warming Up"),
         "marker-adjusting-print-quality": qsTr("Marker Adjusting Print Quality"),
         "marker-cleaner-missing": qsTr("Marker Cleaner Missing"),
         "marker-developer-almost-empty": qsTr("Marker Developer Almost Empty"),
         "marker-developer-empty": qsTr("Marker Developer Empty"),
         "marker-developer-missing": qsTr("Marker Developer Missing"),
         "marker-fuser-missing": qsTr("Marker Fuser Missing"),
         "marker-fuser-thermistor-failure": qsTr("Marker Fuser Thermistor Failure"),
         "marker-fuser-timing-failure": qsTr("Marker Fuser Timing Failure"),
         "marker-ink-almost-empty": qsTr("Marker Ink Almost Empty"),
         "marker-ink-empty": qsTr("Marker Ink Empty"),
         "marker-ink-missing": qsTr("Marker Ink Missing"),
         "marker-opc-missing": qsTr("Marker Opc Missing"),
         "marker-print-ribbon-almost-empty": qsTr("Marker Print Ribbon Almost Empty"),
         "marker-print-ribbon-empty": qsTr("Marker Print Ribbon Empty"),
         "marker-print-ribbon-missing": qsTr("Marker Print Ribbon Missing"),
         "marker-supply-almost-empty": qsTr("Marker Supply Almost Empty"),
         "marker-supply-empty": qsTr("Ink/toner empty"),
         "marker-supply-low": qsTr("Ink/toner low"),
         "marker-supply-missing": qsTr("Marker Supply Missing"),
         "marker-toner-cartridge-missing": qsTr("Marker Toner Cartridge Missing"),
         "marker-toner-missing": qsTr("Marker Toner Missing"),
         "marker-waste-almost-full": qsTr("Ink/toner waste bin almost full"),
         "marker-waste-full": qsTr("Ink/toner waste bin full"),
         "marker-waste-ink-receptacle-almost-full": qsTr("Marker Waste Ink Receptacle Almost Full"),
         "marker-waste-ink-receptacle-full": qsTr("Marker Waste Ink Receptacle Full"),
         "marker-waste-ink-receptacle-missing": qsTr("Marker Waste Ink Receptacle Missing"),
         "marker-waste-missing": qsTr("Marker Waste Missing"),
         "marker-waste-toner-receptacle-almost-full": qsTr("Marker Waste Toner Receptacle Almost Full"),
         "marker-waste-toner-receptacle-full": qsTr("Marker Waste Toner Receptacle Full"),
         "marker-waste-toner-receptacle-missing": qsTr("Marker Waste Toner Receptacle Missing"),
         "material-empty": qsTr("Material Empty"),
         "material-low": qsTr("Material Low"),
         "material-needed": qsTr("Material Needed"),
         "media-drying": qsTr("Media Drying"),
         "media-empty": qsTr("Paper tray is empty"),
         "media-jam": qsTr("Paper jam"),
         "media-low": qsTr("Paper tray is almost empty"),
         "media-needed": qsTr("Load paper"),
         "media-path-cannot-duplex-media-selected": qsTr("Media Path Cannot Do 2-Sided Printing"),
         "media-path-failure": qsTr("Media Path Failure"),
         "media-path-input-empty": qsTr("Media Path Input Empty"),
         "media-path-input-feed-error": qsTr("Media Path Input Feed Error"),
         "media-path-input-jam": qsTr("Media Path Input Jam"),
         "media-path-input-request": qsTr("Media Path Input Request"),
         "media-path-jam": qsTr("Media Path Jam"),
         "media-path-media-tray-almost-full": qsTr("Media Path Media Tray Almost Full"),
         "media-path-media-tray-full": qsTr("Media Path Media Tray Full"),
         "media-path-media-tray-missing": qsTr("Media Path Media Tray Missing"),
         "media-path-output-feed-error": qsTr("Media Path Output Feed Error"),
         "media-path-output-full": qsTr("Media Path Output Full"),
         "media-path-output-jam": qsTr("Media Path Output Jam"),
         "media-path-pick-roller-failure": qsTr("Media Path Pick Roller Failure"),
         "media-path-pick-roller-life-over": qsTr("Media Path Pick Roller Life Over"),
         "media-path-pick-roller-life-warn": qsTr("Media Path Pick Roller Life Warn"),
         "media-path-pick-roller-missing": qsTr("Media Path Pick Roller Missing"),
         "motor-failure": qsTr("Motor Failure"),
         "moving-to-paused": qsTr("Printer going offline"),
         "none": "", //"None",
         "opc-life-over": qsTr("Optical Photoconductor Life Over"),
         "opc-near-eol": qsTr("OPC almost at end-of-life"),
         "other": qsTr("Check the printer for errors"),
         "output-area-almost-full": qsTr("Output bin is almost full"),
         "output-area-full": qsTr("Output bin is full"),
         "output-mailbox-select-failure": qsTr("Output Mailbox Select Failure"),
         "output-media-tray-failure": qsTr("Output Media Tray Failure"),
         "output-media-tray-feed-error": qsTr("Output Media Tray Feed Error"),
         "output-media-tray-jam": qsTr("Output Media Tray Jam"),
         "output-tray-missing": qsTr("Output tray is missing"),
         "paused": qsTr("Paused"),
         "perforater-added": qsTr("Perforater Added"),
         "perforater-almost-empty": qsTr("Perforater Almost Empty"),
         "perforater-almost-full": qsTr("Perforater Almost Full"),
         "perforater-at-limit": qsTr("Perforater At Limit"),
         "perforater-closed": qsTr("Perforater Closed"),
         "perforater-configuration-change": qsTr("Perforater Configuration Change"),
         "perforater-cover-closed": qsTr("Perforater Cover Closed"),
         "perforater-cover-open": qsTr("Perforater Cover Open"),
         "perforater-empty": qsTr("Perforater Empty"),
         "perforater-full": qsTr("Perforater Full"),
         "perforater-interlock-closed": qsTr("Perforater Interlock Closed"),
         "perforater-interlock-open": qsTr("Perforater Interlock Open"),
         "perforater-jam": qsTr("Perforater Jam"),
         "perforater-life-almost-over": qsTr("Perforater Life Almost Over"),
         "perforater-life-over": qsTr("Perforater Life Over"),
         "perforater-memory-exhausted": qsTr("Perforater Memory Exhausted"),
         "perforater-missing": qsTr("Perforater Missing"),
         "perforater-motor-failure": qsTr("Perforater Motor Failure"),
         "perforater-near-limit": qsTr("Perforater Near Limit"),
         "perforater-offline": qsTr("Perforater Offline"),
         "perforater-opened": qsTr("Perforater Opened"),
         "perforater-over-temperature": qsTr("Perforater Over Temperature"),
         "perforater-power-saver": qsTr("Perforater Power Saver"),
         "perforater-recoverable-failure": qsTr("Perforater Recoverable Failure"),
         "perforater-recoverable-storage": qsTr("Perforater Recoverable Storage"),
         "perforater-removed": qsTr("Perforater Removed"),
         "perforater-resource-added": qsTr("Perforater Resource Added"),
         "perforater-resource-removed": qsTr("Perforater Resource Removed"),
         "perforater-thermistor-failure": qsTr("Perforater Thermistor Failure"),
         "perforater-timing-failure": qsTr("Perforater Timing Failure"),
         "perforater-turned-off": qsTr("Perforater Turned Off"),
         "perforater-turned-on": qsTr("Perforater Turned On"),
         "perforater-under-temperature": qsTr("Perforater Under Temperature"),
         "perforater-unrecoverable-failure": qsTr("Perforater Unrecoverable Failure"),
         "perforater-unrecoverable-storage-error": qsTr("Perforater Unrecoverable Storage Error"),
         "perforater-warming-up": qsTr("Perforater Warming Up"),
         "platform-cooling": qsTr("Platform Cooling"),
         "platform-failure": qsTr("Platform Failure"),
         "platform-heating": qsTr("Platform Heating"),
         "platform-temperature-high": qsTr("Platform Temperature High"),
         "platform-temperature-low": qsTr("Platform Temperature Low"),
         "power-down": qsTr("Power Down"),
         "power-up": qsTr("Power Up"),
         "printer-manual-reset": qsTr("Printer Reset Manually"),
         "printer-nms-reset": qsTr("Printer Reset Remotely"),
         "printer-ready-to-print": qsTr("Printer Ready To Print"),
         "puncher-added": qsTr("Puncher Added"),
         "puncher-almost-empty": qsTr("Puncher Almost Empty"),
         "puncher-almost-full": qsTr("Puncher Almost Full"),
         "puncher-at-limit": qsTr("Puncher At Limit"),
         "puncher-closed": qsTr("Puncher Closed"),
         "puncher-configuration-change": qsTr("Puncher Configuration Change"),
         "puncher-cover-closed": qsTr("Puncher Cover Closed"),
         "puncher-cover-open": qsTr("Puncher Cover Open"),
         "puncher-empty": qsTr("Puncher Empty"),
         "puncher-full": qsTr("Puncher Full"),
         "puncher-interlock-closed": qsTr("Puncher Interlock Closed"),
         "puncher-interlock-open": qsTr("Puncher Interlock Open"),
         "puncher-jam": qsTr("Puncher Jam"),
         "puncher-life-almost-over": qsTr("Puncher Life Almost Over"),
         "puncher-life-over": qsTr("Puncher Life Over"),
         "puncher-memory-exhausted": qsTr("Puncher Memory Exhausted"),
         "puncher-missing": qsTr("Puncher Missing"),
         "puncher-motor-failure": qsTr("Puncher Motor Failure"),
         "puncher-near-limit": qsTr("Puncher Near Limit"),
         "puncher-offline": qsTr("Puncher Offline"),
         "puncher-opened": qsTr("Puncher Opened"),
         "puncher-over-temperature": qsTr("Puncher Over Temperature"),
         "puncher-power-saver": qsTr("Puncher Power Saver"),
         "puncher-recoverable-failure": qsTr("Puncher Recoverable Failure"),
         "puncher-recoverable-storage": qsTr("Puncher Recoverable Storage"),
         "puncher-removed": qsTr("Puncher Removed"),
         "puncher-resource-added": qsTr("Puncher Resource Added"),
         "puncher-resource-removed": qsTr("Puncher Resource Removed"),
         "puncher-thermistor-failure": qsTr("Puncher Thermistor Failure"),
         "puncher-timing-failure": qsTr("Puncher Timing Failure"),
         "puncher-turned-off": qsTr("Puncher Turned Off"),
         "puncher-turned-on": qsTr("Puncher Turned On"),
         "puncher-under-temperature": qsTr("Puncher Under Temperature"),
         "puncher-unrecoverable-failure": qsTr("Puncher Unrecoverable Failure"),
         "puncher-unrecoverable-storage-error": qsTr("Puncher Unrecoverable Storage Error"),
         "puncher-warming-up": qsTr("Puncher Warming Up"),
         "scan-media-path-failure": qsTr("Scan Media Path Failure"),
         "scan-media-path-input-feed-error": qsTr("Scan Media Path Input Feed Error"),
         "scan-media-path-input-jam": qsTr("Scan Media Path Input Jam"),
         "scan-media-path-input-request": qsTr("Scan Media Path Input Request"),
         "scan-media-path-jam": qsTr("Scan Media Path Jam"),
         "scan-media-path-output-feed-error": qsTr("Scan Media Path Output Feed Error"),
         "scan-media-path-output-full": qsTr("Scan Media Path Output Full"),
         "scan-media-path-output-jam": qsTr("Scan Media Path Output Jam"),
         "scan-media-path-pick-roller-failure": qsTr("Scan Media Path Pick Roller Failure"),
         "scan-media-path-pick-roller-life-over": qsTr("Scan Media Path Pick Roller Life Over"),
         "scan-media-path-pick-roller-life-warn": qsTr("Scan Media Path Pick Roller Life Warn"),
         "scan-media-path-pick-roller-missing": qsTr("Scan Media Path Pick Roller Missing"),
         "scan-media-path-tray-almost-full": qsTr("Scan Media Path Tray Almost Full"),
         "scan-media-path-tray-full": qsTr("Scan Media Path Tray Full"),
         "scan-media-path-tray-missing": qsTr("Scan Media Path Tray Missing"),
         "scanner-light-failure": qsTr("Scanner Light Failure"),
         "scanner-light-life-almost-over": qsTr("Scanner Light Life Almost Over"),
         "scanner-light-life-over": qsTr("Scanner Light Life Over"),
         "scanner-light-missing": qsTr("Scanner Light Missing"),
         "scanner-sensor-failure": qsTr("Scanner Sensor Failure"),
         "scanner-sensor-life-almost-over": qsTr("Scanner Sensor Life Almost Over"),
         "scanner-sensor-life-over": qsTr("Scanner Sensor Life Over"),
         "scanner-sensor-missing": qsTr("Scanner Sensor Missing"),
         "separation-cutter-added": qsTr("Separation Cutter Added"),
         "separation-cutter-almost-empty": qsTr("Separation Cutter Almost Empty"),
         "separation-cutter-almost-full": qsTr("Separation Cutter Almost Full"),
         "separation-cutter-at-limit": qsTr("Separation Cutter At Limit"),
         "separation-cutter-closed": qsTr("Separation Cutter Closed"),
         "separation-cutter-configuration-change": qsTr("Separation Cutter Configuration Change"),
         "separation-cutter-cover-closed": qsTr("Separation Cutter Cover Closed"),
         "separation-cutter-cover-open": qsTr("Separation Cutter Cover Open"),
         "separation-cutter-empty": qsTr("Separation Cutter Empty"),
         "separation-cutter-full": qsTr("Separation Cutter Full"),
         "separation-cutter-interlock-closed": qsTr("Separation Cutter Interlock Closed"),
         "separation-cutter-interlock-open": qsTr("Separation Cutter Interlock Open"),
         "separation-cutter-jam": qsTr("Separation Cutter Jam"),
         "separation-cutter-life-almost-over": qsTr("Separation Cutter Life Almost Over"),
         "separation-cutter-life-over": qsTr("Separation Cutter Life Over"),
         "separation-cutter-memory-exhausted": qsTr("Separation Cutter Memory Exhausted"),
         "separation-cutter-missing": qsTr("Separation Cutter Missing"),
         "separation-cutter-motor-failure": qsTr("Separation Cutter Motor Failure"),
         "separation-cutter-near-limit": qsTr("Separation Cutter Near Limit"),
         "separation-cutter-offline": qsTr("Separation Cutter Offline"),
         "separation-cutter-opened": qsTr("Separation Cutter Opened"),
         "separation-cutter-over-temperature": qsTr("Separation Cutter Over Temperature"),
         "separation-cutter-power-saver": qsTr("Separation Cutter Power Saver"),
         "separation-cutter-recoverable-failure": qsTr("Separation Cutter Recoverable Failure"),
         "separation-cutter-recoverable-storage": qsTr("Separation Cutter Recoverable Storage"),
         "separation-cutter-removed": qsTr("Separation Cutter Removed"),
         "separation-cutter-resource-added": qsTr("Separation Cutter Resource Added"),
         "separation-cutter-resource-removed": qsTr("Separation Cutter Resource Removed"),
         "separation-cutter-thermistor-failure": qsTr("Separation Cutter Thermistor Failure"),
         "separation-cutter-timing-failure": qsTr("Separation Cutter Timing Failure"),
         "separation-cutter-turned-off": qsTr("Separation Cutter Turned Off"),
         "separation-cutter-turned-on": qsTr("Separation Cutter Turned On"),
         "separation-cutter-under-temperature": qsTr("Separation Cutter Under Temperature"),
         "separation-cutter-unrecoverable-failure": qsTr("Separation Cutter Unrecoverable Failure"),
         "separation-cutter-unrecoverable-storage-error": qsTr("Separation Cutter Unrecoverable Storage Error"),
         "separation-cutter-warming-up": qsTr("Separation Cutter Warming Up"),
         "sheet-rotator-added": qsTr("Sheet Rotator Added"),
         "sheet-rotator-almost-empty": qsTr("Sheet Rotator Almost Empty"),
         "sheet-rotator-almost-full": qsTr("Sheet Rotator Almost Full"),
         "sheet-rotator-at-limit": qsTr("Sheet Rotator At Limit"),
         "sheet-rotator-closed": qsTr("Sheet Rotator Closed"),
         "sheet-rotator-configuration-change": qsTr("Sheet Rotator Configuration Change"),
         "sheet-rotator-cover-closed": qsTr("Sheet Rotator Cover Closed"),
         "sheet-rotator-cover-open": qsTr("Sheet Rotator Cover Open"),
         "sheet-rotator-empty": qsTr("Sheet Rotator Empty"),
         "sheet-rotator-full": qsTr("Sheet Rotator Full"),
         "sheet-rotator-interlock-closed": qsTr("Sheet Rotator Interlock Closed"),
         "sheet-rotator-interlock-open": qsTr("Sheet Rotator Interlock Open"),
         "sheet-rotator-jam": qsTr("Sheet Rotator Jam"),
         "sheet-rotator-life-almost-over": qsTr("Sheet Rotator Life Almost Over"),
         "sheet-rotator-life-over": qsTr("Sheet Rotator Life Over"),
         "sheet-rotator-memory-exhausted": qsTr("Sheet Rotator Memory Exhausted"),
         "sheet-rotator-missing": qsTr("Sheet Rotator Missing"),
         "sheet-rotator-motor-failure": qsTr("Sheet Rotator Motor Failure"),
         "sheet-rotator-near-limit": qsTr("Sheet Rotator Near Limit"),
         "sheet-rotator-offline": qsTr("Sheet Rotator Offline"),
         "sheet-rotator-opened": qsTr("Sheet Rotator Opened"),
         "sheet-rotator-over-temperature": qsTr("Sheet Rotator Over Temperature"),
         "sheet-rotator-power-saver": qsTr("Sheet Rotator Power Saver"),
         "sheet-rotator-recoverable-failure": qsTr("Sheet Rotator Recoverable Failure"),
         "sheet-rotator-recoverable-storage": qsTr("Sheet Rotator Recoverable Storage"),
         "sheet-rotator-removed": qsTr("Sheet Rotator Removed"),
         "sheet-rotator-resource-added": qsTr("Sheet Rotator Resource Added"),
         "sheet-rotator-resource-removed": qsTr("Sheet Rotator Resource Removed"),
         "sheet-rotator-thermistor-failure": qsTr("Sheet Rotator Thermistor Failure"),
         "sheet-rotator-timing-failure": qsTr("Sheet Rotator Timing Failure"),
         "sheet-rotator-turned-off": qsTr("Sheet Rotator Turned Off"),
         "sheet-rotator-turned-on": qsTr("Sheet Rotator Turned On"),
         "sheet-rotator-under-temperature": qsTr("Sheet Rotator Under Temperature"),
         "sheet-rotator-unrecoverable-failure": qsTr("Sheet Rotator Unrecoverable Failure"),
         "sheet-rotator-unrecoverable-storage-error": qsTr("Sheet Rotator Unrecoverable Storage Error"),
         "sheet-rotator-warming-up": qsTr("Sheet Rotator Warming Up"),
         "shutdown": qsTr("Printer offline"),
         "slitter-added": qsTr("Slitter Added"),
         "slitter-almost-empty": qsTr("Slitter Almost Empty"),
         "slitter-almost-full": qsTr("Slitter Almost Full"),
         "slitter-at-limit": qsTr("Slitter At Limit"),
         "slitter-closed": qsTr("Slitter Closed"),
         "slitter-configuration-change": qsTr("Slitter Configuration Change"),
         "slitter-cover-closed": qsTr("Slitter Cover Closed"),
         "slitter-cover-open": qsTr("Slitter Cover Open"),
         "slitter-empty": qsTr("Slitter Empty"),
         "slitter-full": qsTr("Slitter Full"),
         "slitter-interlock-closed": qsTr("Slitter Interlock Closed"),
         "slitter-interlock-open": qsTr("Slitter Interlock Open"),
         "slitter-jam": qsTr("Slitter Jam"),
         "slitter-life-almost-over": qsTr("Slitter Life Almost Over"),
         "slitter-life-over": qsTr("Slitter Life Over"),
         "slitter-memory-exhausted": qsTr("Slitter Memory Exhausted"),
         "slitter-missing": qsTr("Slitter Missing"),
         "slitter-motor-failure": qsTr("Slitter Motor Failure"),
         "slitter-near-limit": qsTr("Slitter Near Limit"),
         "slitter-offline": qsTr("Slitter Offline"),
         "slitter-opened": qsTr("Slitter Opened"),
         "slitter-over-temperature": qsTr("Slitter Over Temperature"),
         "slitter-power-saver": qsTr("Slitter Power Saver"),
         "slitter-recoverable-failure": qsTr("Slitter Recoverable Failure"),
         "slitter-recoverable-storage": qsTr("Slitter Recoverable Storage"),
         "slitter-removed": qsTr("Slitter Removed"),
         "slitter-resource-added": qsTr("Slitter Resource Added"),
         "slitter-resource-removed": qsTr("Slitter Resource Removed"),
         "slitter-thermistor-failure": qsTr("Slitter Thermistor Failure"),
         "slitter-timing-failure": qsTr("Slitter Timing Failure"),
         "slitter-turned-off": qsTr("Slitter Turned Off"),
         "slitter-turned-on": qsTr("Slitter Turned On"),
         "slitter-under-temperature": qsTr("Slitter Under Temperature"),
         "slitter-unrecoverable-failure": qsTr("Slitter Unrecoverable Failure"),
         "slitter-unrecoverable-storage-error": qsTr("Slitter Unrecoverable Storage Error"),
         "slitter-warming-up": qsTr("Slitter Warming Up"),
         "spool-area-full": qsTr("Spool Area Full"),
         "stacker-added": qsTr("Stacker Added"),
         "stacker-almost-empty": qsTr("Stacker Almost Empty"),
         "stacker-almost-full": qsTr("Stacker Almost Full"),
         "stacker-at-limit": qsTr("Stacker At Limit"),
         "stacker-closed": qsTr("Stacker Closed"),
         "stacker-configuration-change": qsTr("Stacker Configuration Change"),
         "stacker-cover-closed": qsTr("Stacker Cover Closed"),
         "stacker-cover-open": qsTr("Stacker Cover Open"),
         "stacker-empty": qsTr("Stacker Empty"),
         "stacker-full": qsTr("Stacker Full"),
         "stacker-interlock-closed": qsTr("Stacker Interlock Closed"),
         "stacker-interlock-open": qsTr("Stacker Interlock Open"),
         "stacker-jam": qsTr("Stacker Jam"),
         "stacker-life-almost-over": qsTr("Stacker Life Almost Over"),
         "stacker-life-over": qsTr("Stacker Life Over"),
         "stacker-memory-exhausted": qsTr("Stacker Memory Exhausted"),
         "stacker-missing": qsTr("Stacker Missing"),
         "stacker-motor-failure": qsTr("Stacker Motor Failure"),
         "stacker-near-limit": qsTr("Stacker Near Limit"),
         "stacker-offline": qsTr("Stacker Offline"),
         "stacker-opened": qsTr("Stacker Opened"),
         "stacker-over-temperature": qsTr("Stacker Over Temperature"),
         "stacker-power-saver": qsTr("Stacker Power Saver"),
         "stacker-recoverable-failure": qsTr("Stacker Recoverable Failure"),
         "stacker-recoverable-storage": qsTr("Stacker Recoverable Storage"),
         "stacker-removed": qsTr("Stacker Removed"),
         "stacker-resource-added": qsTr("Stacker Resource Added"),
         "stacker-resource-removed": qsTr("Stacker Resource Removed"),
         "stacker-thermistor-failure": qsTr("Stacker Thermistor Failure"),
         "stacker-timing-failure": qsTr("Stacker Timing Failure"),
         "stacker-turned-off": qsTr("Stacker Turned Off"),
         "stacker-turned-on": qsTr("Stacker Turned On"),
         "stacker-under-temperature": qsTr("Stacker Under Temperature"),
         "stacker-unrecoverable-failure": qsTr("Stacker Unrecoverable Failure"),
         "stacker-unrecoverable-storage-error": qsTr("Stacker Unrecoverable Storage Error"),
         "stacker-warming-up": qsTr("Stacker Warming Up"),
         "stapler-added": qsTr("Stapler Added"),
         "stapler-almost-empty": qsTr("Stapler Almost Empty"),
         "stapler-almost-full": qsTr("Stapler Almost Full"),
         "stapler-at-limit": qsTr("Stapler At Limit"),
         "stapler-closed": qsTr("Stapler Closed"),
         "stapler-configuration-change": qsTr("Stapler Configuration Change"),
         "stapler-cover-closed": qsTr("Stapler Cover Closed"),
         "stapler-cover-open": qsTr("Stapler Cover Open"),
         "stapler-empty": qsTr("Stapler Empty"),
         "stapler-full": qsTr("Stapler Full"),
         "stapler-interlock-closed": qsTr("Stapler Interlock Closed"),
         "stapler-interlock-open": qsTr("Stapler Interlock Open"),
         "stapler-jam": qsTr("Stapler Jam"),
         "stapler-life-almost-over": qsTr("Stapler Life Almost Over"),
         "stapler-life-over": qsTr("Stapler Life Over"),
         "stapler-memory-exhausted": qsTr("Stapler Memory Exhausted"),
         "stapler-missing": qsTr("Stapler Missing"),
         "stapler-motor-failure": qsTr("Stapler Motor Failure"),
         "stapler-near-limit": qsTr("Stapler Near Limit"),
         "stapler-offline": qsTr("Stapler Offline"),
         "stapler-opened": qsTr("Stapler Opened"),
         "stapler-over-temperature": qsTr("Stapler Over Temperature"),
         "stapler-power-saver": qsTr("Stapler Power Saver"),
         "stapler-recoverable-failure": qsTr("Stapler Recoverable Failure"),
         "stapler-recoverable-storage": qsTr("Stapler Recoverable Storage"),
         "stapler-removed": qsTr("Stapler Removed"),
         "stapler-resource-added": qsTr("Stapler Resource Added"),
         "stapler-resource-removed": qsTr("Stapler Resource Removed"),
         "stapler-thermistor-failure": qsTr("Stapler Thermistor Failure"),
         "stapler-timing-failure": qsTr("Stapler Timing Failure"),
         "stapler-turned-off": qsTr("Stapler Turned Off"),
         "stapler-turned-on": qsTr("Stapler Turned On"),
         "stapler-under-temperature": qsTr("Stapler Under Temperature"),
         "stapler-unrecoverable-failure": qsTr("Stapler Unrecoverable Failure"),
         "stapler-unrecoverable-storage-error": qsTr("Stapler Unrecoverable Storage Error"),
         "stapler-warming-up": qsTr("Stapler Warming Up"),
         "stitcher-added": qsTr("Stitcher Added"),
         "stitcher-almost-empty": qsTr("Stitcher Almost Empty"),
         "stitcher-almost-full": qsTr("Stitcher Almost Full"),
         "stitcher-at-limit": qsTr("Stitcher At Limit"),
         "stitcher-closed": qsTr("Stitcher Closed"),
         "stitcher-configuration-change": qsTr("Stitcher Configuration Change"),
         "stitcher-cover-closed": qsTr("Stitcher Cover Closed"),
         "stitcher-cover-open": qsTr("Stitcher Cover Open"),
         "stitcher-empty": qsTr("Stitcher Empty"),
         "stitcher-full": qsTr("Stitcher Full"),
         "stitcher-interlock-closed": qsTr("Stitcher Interlock Closed"),
         "stitcher-interlock-open": qsTr("Stitcher Interlock Open"),
         "stitcher-jam": qsTr("Stitcher Jam"),
         "stitcher-life-almost-over": qsTr("Stitcher Life Almost Over"),
         "stitcher-life-over": qsTr("Stitcher Life Over"),
         "stitcher-memory-exhausted": qsTr("Stitcher Memory Exhausted"),
         "stitcher-missing": qsTr("Stitcher Missing"),
         "stitcher-motor-failure": qsTr("Stitcher Motor Failure"),
         "stitcher-near-limit": qsTr("Stitcher Near Limit"),
         "stitcher-offline": qsTr("Stitcher Offline"),
         "stitcher-opened": qsTr("Stitcher Opened"),
         "stitcher-over-temperature": qsTr("Stitcher Over Temperature"),
         "stitcher-power-saver": qsTr("Stitcher Power Saver"),
         "stitcher-recoverable-failure": qsTr("Stitcher Recoverable Failure"),
         "stitcher-recoverable-storage": qsTr("Stitcher Recoverable Storage"),
         "stitcher-removed": qsTr("Stitcher Removed"),
         "stitcher-resource-added": qsTr("Stitcher Resource Added"),
         "stitcher-resource-removed": qsTr("Stitcher Resource Removed"),
         "stitcher-thermistor-failure": qsTr("Stitcher Thermistor Failure"),
         "stitcher-timing-failure": qsTr("Stitcher Timing Failure"),
         "stitcher-turned-off": qsTr("Stitcher Turned Off"),
         "stitcher-turned-on": qsTr("Stitcher Turned On"),
         "stitcher-under-temperature": qsTr("Stitcher Under Temperature"),
         "stitcher-unrecoverable-failure": qsTr("Stitcher Unrecoverable Failure"),
         "stitcher-unrecoverable-storage-error": qsTr("Stitcher Unrecoverable Storage Error"),
         "stitcher-warming-up": qsTr("Stitcher Warming Up"),
         "stopped-partly": qsTr("Partially stopped"),
         "stopping": qsTr("Stopping"),
         "subunit-added": qsTr("Subunit Added"),
         "subunit-almost-empty": qsTr("Subunit Almost Empty"),
         "subunit-almost-full": qsTr("Subunit Almost Full"),
         "subunit-at-limit": qsTr("Subunit At Limit"),
         "subunit-closed": qsTr("Subunit Closed"),
         "subunit-cooling-down": qsTr("Subunit Cooling Down"),
         "subunit-empty": qsTr("Subunit Empty"),
         "subunit-full": qsTr("Subunit Full"),
         "subunit-life-almost-over": qsTr("Subunit Life Almost Over"),
         "subunit-life-over": qsTr("Subunit Life Over"),
         "subunit-memory-exhausted": qsTr("Subunit Memory Exhausted"),
         "subunit-missing": qsTr("Subunit Missing"),
         "subunit-motor-failure": qsTr("Subunit Motor Failure"),
         "subunit-near-limit": qsTr("Subunit Near Limit"),
         "subunit-offline": qsTr("Subunit Offline"),
         "subunit-opened": qsTr("Subunit Opened"),
         "subunit-over-temperature": qsTr("Subunit Over Temperature"),
         "subunit-power-saver": qsTr("Subunit Power Saver"),
         "subunit-recoverable-failure": qsTr("Subunit Recoverable Failure"),
         "subunit-recoverable-storage": qsTr("Subunit Recoverable Storage"),
         "subunit-removed": qsTr("Subunit Removed"),
         "subunit-resource-added": qsTr("Subunit Resource Added"),
         "subunit-resource-removed": qsTr("Subunit Resource Removed"),
         "subunit-thermistor-failure": qsTr("Subunit Thermistor Failure"),
         "subunit-timing-Failure": qsTr("Subunit Timing Failure"),
         "subunit-turned-off": qsTr("Subunit Turned Off"),
         "subunit-turned-on": qsTr("Subunit Turned On"),
         "subunit-under-temperature": qsTr("Subunit Under Temperature"),
         "subunit-unrecoverable-failure": qsTr("Subunit Unrecoverable Failure"),
         "subunit-unrecoverable-storage": qsTr("Subunit Unrecoverable Storage"),
         "subunit-warming-up": qsTr("Subunit Warming Up"),
         "timed-out": qsTr("Printer stopped responding"),
         "toner-empty": qsTr("Out of toner"),
         "toner-low": qsTr("Toner low"),
         "trimmer-added": qsTr("Trimmer Added"),
         "trimmer-almost-empty": qsTr("Trimmer Almost Empty"),
         "trimmer-almost-full": qsTr("Trimmer Almost Full"),
         "trimmer-at-limit": qsTr("Trimmer At Limit"),
         "trimmer-closed": qsTr("Trimmer Closed"),
         "trimmer-configuration-change": qsTr("Trimmer Configuration Change"),
         "trimmer-cover-closed": qsTr("Trimmer Cover Closed"),
         "trimmer-cover-open": qsTr("Trimmer Cover Open"),
         "trimmer-empty": qsTr("Trimmer Empty"),
         "trimmer-full": qsTr("Trimmer Full"),
         "trimmer-interlock-closed": qsTr("Trimmer Interlock Closed"),
         "trimmer-interlock-open": qsTr("Trimmer Interlock Open"),
         "trimmer-jam": qsTr("Trimmer Jam"),
         "trimmer-life-almost-over": qsTr("Trimmer Life Almost Over"),
         "trimmer-life-over": qsTr("Trimmer Life Over"),
         "trimmer-memory-exhausted": qsTr("Trimmer Memory Exhausted"),
         "trimmer-missing": qsTr("Trimmer Missing"),
         "trimmer-motor-failure": qsTr("Trimmer Motor Failure"),
         "trimmer-near-limit": qsTr("Trimmer Near Limit"),
         "trimmer-offline": qsTr("Trimmer Offline"),
         "trimmer-opened": qsTr("Trimmer Opened"),
         "trimmer-over-temperature": qsTr("Trimmer Over Temperature"),
         "trimmer-power-saver": qsTr("Trimmer Power Saver"),
         "trimmer-recoverable-failure": qsTr("Trimmer Recoverable Failure"),
         "trimmer-recoverable-storage": qsTr("Trimmer Recoverable Storage"),
         "trimmer-removed": qsTr("Trimmer Removed"),
         "trimmer-resource-added": qsTr("Trimmer Resource Added"),
         "trimmer-resource-removed": qsTr("Trimmer Resource Removed"),
         "trimmer-thermistor-failure": qsTr("Trimmer Thermistor Failure"),
         "trimmer-timing-failure": qsTr("Trimmer Timing Failure"),
         "trimmer-turned-off": qsTr("Trimmer Turned Off"),
         "trimmer-turned-on": qsTr("Trimmer Turned On"),
         "trimmer-under-temperature": qsTr("Trimmer Under Temperature"),
         "trimmer-unrecoverable-failure": qsTr("Trimmer Unrecoverable Failure"),
         "trimmer-unrecoverable-storage-error": qsTr("Trimmer Unrecoverable Storage Error"),
         "trimmer-warming-up": qsTr("Trimmer Warming Up"),
         "unknown": qsTr("Unknown"),
         "wrapper-added": qsTr("Wrapper Added"),
         "wrapper-almost-empty": qsTr("Wrapper Almost Empty"),
         "wrapper-almost-full": qsTr("Wrapper Almost Full"),
         "wrapper-at-limit": qsTr("Wrapper At Limit"),
         "wrapper-closed": qsTr("Wrapper Closed"),
         "wrapper-configuration-change": qsTr("Wrapper Configuration Change"),
         "wrapper-cover-closed": qsTr("Wrapper Cover Closed"),
         "wrapper-cover-open": qsTr("Wrapper Cover Open"),
         "wrapper-empty": qsTr("Wrapper Empty"),
         "wrapper-full": qsTr("Wrapper Full"),
         "wrapper-interlock-closed": qsTr("Wrapper Interlock Closed"),
         "wrapper-interlock-open": qsTr("Wrapper Interlock Open"),
         "wrapper-jam": qsTr("Wrapper Jam"),
         "wrapper-life-almost-over": qsTr("Wrapper Life Almost Over"),
         "wrapper-life-over": qsTr("Wrapper Life Over"),
         "wrapper-memory-exhausted": qsTr("Wrapper Memory Exhausted"),
         "wrapper-missing": qsTr("Wrapper Missing"),
         "wrapper-motor-failure": qsTr("Wrapper Motor Failure"),
         "wrapper-near-limit": qsTr("Wrapper Near Limit"),
         "wrapper-offline": qsTr("Wrapper Offline"),
         "wrapper-opened": qsTr("Wrapper Opened"),
         "wrapper-over-temperature": qsTr("Wrapper Over Temperature"),
         "wrapper-power-saver": qsTr("Wrapper Power Saver"),
         "wrapper-recoverable-failure": qsTr("Wrapper Recoverable Failure"),
         "wrapper-recoverable-storage": qsTr("Wrapper Recoverable Storage"),
         "wrapper-removed": qsTr("Wrapper Removed"),
         "wrapper-resource-added": qsTr("Wrapper Resource Added"),
         "wrapper-resource-removed": qsTr("Wrapper Resource Removed"),
         "wrapper-thermistor-failure": qsTr("Wrapper Thermistor Failure"),
         "wrapper-timing-failure": qsTr("Wrapper Timing Failure"),
         "wrapper-turned-off": qsTr("Wrapper Turned Off"),
         "wrapper-turned-on": qsTr("Wrapper Turned On"),
         "wrapper-under-temperature": qsTr("Wrapper Under Temperature"),
         "wrapper-unrecoverable-failure": qsTr("Wrapper Unrecoverable Failure"),
         "wrapper-unrecoverable-storage-error": qsTr("Wrapper Unrecoverable Storage Error"),
         "wrapper-warming-up": qsTr("Wrapper Warming Up")}
